plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm'
    id 'com.gradleup.shadow' version '8.3.5'
}

group = 'org.orbis'
version = '1.0.0'

repositories {
    mavenCentral()
    flatDir {
        dirs 'libraries'
    }
    maven {
        name = "hMReleases"
        url = uri("https://maven.hytale-modding.info/releases")
    }

}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

dependencies {
    // Libraries
    compileOnly name: 'HytaleServer'
    
    // Tests
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.3.0" //"org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    implementation "com.buuz135:MultipleHUD:1.0.2"
}

jar {
    if (project.hasProperty('outputDirectory')) {
        destinationDirectory = file(project.property('outputDirectory'))
    }

    manifest {
        attributes["Main-Class"] = "org.orbis.industries.OrbisIndustries"
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

test {
    useJUnitPlatform()
}